version: '3'

# Containers we're going to run.
services:
   # Our Phoenix container.
   api:
      # The build parameters for this container.
      build: ./api
      image: api
      environment:
         # Variables to connect to our Postgres server.
         PGUSER: postgres
         PGPASSWORD: postgres
         PGDATABASE: api_dev
         PGPORT: 5432
         # Hostname of our Postgres container.
         PGHOST: db
      ports:
         # Mapping the port to make the Phoenix app accessible outside of the container.
         - '4000:4000'
      depends_on:
         # The DB container needs to be started before we start this container.
         - db
      
   db:
      # We use the predefined Postgres image.
      image: postgres:9.6
      environment:
         # Set user/password for Postgres.
         POSTGRES_USER: postgres
         POSTGRES_PASSWORD: postgres
         PGDATABASE: api_dev
         PGDATA: /var/lib/postgresql/data/pgdata
      restart: always
      volumes:
          - "/var/run/postgres/postgres.sock:/var/run/postgres/postgres.sock"
          - "dbdata:/var/lib/postgresql/data"

   front:
      build: ./front-end
      image: front
      restart: always
      depends_on:
          - api
      ports:
          - "3000:3000"
      expose:
          - 3000
      volumes:
      - ./front-end/:/code/
      - /code/node_modules


volumes:
    dbdata: